version: 2
jobs:
  build:
    docker:
      - image: hseeberger/scala-sbt:11.0.4_1.3.2_2.13.1
    working_directory: ~/aws-effect
    steps:
      - checkout
      - restore_cache:
          keys:
            - ivy
      - run:
          command: |
            sbt ";set Global / patchVersion := Some(\"$CIRCLE_BUILD_NUM\");test;+publish;writeVersion"
      - run: git tag $(cat ./version.txt) && git push --tags
      - save_cache:
          key: ivy
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: release
          filters:
            tags:
              ignore: /.*/
